name: CD fastapi app workflow

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract metadata (labels, tags) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: phen0mena1/hng12-stage2-fastapiwithnginx:latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: phen0mena1/hng12-stage2-fastapiwithnginx:latest
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.yml, nginx/nginx.conf"
          target: .
      - name: Run docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker-compose down
            docker rmi -f $(docker images -q)
            docker-compose pull
            docker-compose up -d
